### ISSUE TITLE
[nextagea_moveit_config] Nextage head always in collision in MoveIt

### ISSUE THREAD

**Issue by the-raspberry-pi-guy** [ipab-slmc/nextagea#30]
Upon running ```roslaunch nextagea_moveit_config demo.launch``` (or also just running the move_group and adding motion planning in Rviz manually), the head of the Nextage is always in collision:
![image](https://user-images.githubusercontent.com/5570173/107658548-2194a180-6c7e-11eb-9bf2-1d6e59b710f9.png)

This means that no planning can be done to move the head in any direction. @christian-rauch does not have this issue in his configuration but is using Ubuntu 20, not 18. Could be a version issue?

**Comment by wxmerkt** [comment]
> Ubuntu 20, not 18. Could be a version issue?

Quite possibly - the default behaviour of interpreting using `visual` geometries for missing `collision` geometries changed from Melodic to Noetic. You have two choices: i) explicitly add the exclusion to the URDF, ii) add a collision geometry if none is specified.

**Comment by the-raspberry-pi-guy** [comment]
Thanks @wxmerkt. I have explicitly disabled the collision between the offending links in the SRDF now and this has solved the issue. PR inbound :))
