### ISSUE TITLE
arm joint limits are too conservative

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/nextagea#42]
The arm joint limits are too conservative. The lower arm joints can go into reasonable states outside of the URDF limits. Having the robot initialised outside of these limits prevents us from commanding the robot via MoveIt.

**Comment by the-raspberry-pi-guy** [comment]
As far as I am aware, the limits are the ones from Kawada, right @VladimirIvan ? It is possible that they are too conservative, but I don't think that we edited them

**Comment by christian-rauch** [comment]
I guess it's 672767b356fcdec99076227e42bf2a1eed55a94d that reduced the limtis for `LARM_JOINT4` and `RARM_JOINT4` by more than 0.5 rad. Can we just revert that commit?

**Comment by the-raspberry-pi-guy** [comment]
Apologies, I was mistaken in that case. I think I do recall changes due to the sensor box being mounted onto the arm

**Comment by VladimirIvan** [comment]
Maybe start the robot without servoing and move the joint to the limit. If it's safe, then let's revert. If not, you can find a new limit that works better.

**Comment by VladimirIvan** [comment]
That change should stay. It makes it harder to overwrite the robot_description by accident. The aim was to load the URDF only in one launch file and this should be the hardware driver.

Have you pulled the changes on the robot where the driver launch file loads them from?

**Comment by christian-rauch** [comment]
This should be a save configuration:

LARM_JOINT4: -3.3957119109109284
RARM_JOINT4: -3.2432802400187324

```
name: 
  - CHEST_JOINT0
  - HEAD_JOINT0
  - HEAD_JOINT1
  - LARM_JOINT0
  - LARM_JOINT1
  - LARM_JOINT2
  - LARM_JOINT3
  - LARM_JOINT4
  - LARM_JOINT5
  - RARM_JOINT0
  - RARM_JOINT1
  - RARM_JOINT2
  - RARM_JOINT3
  - RARM_JOINT4
  - RARM_JOINT5
position: [-0.4302097056524902, 0.6986208702267576, -0.15148060280370707, 0.3093619230616274, -0.25996906981360407, 0.41005223936168045, 0.0525081623693255, -3.3957119109109284, 2.710007158918168, 0.2901597706989875, -0.06489203575419258, 0.011400266309968288, 0.016689710972195775, -3.2432802400187324, -0.3712233506683252]
```

![PXL_20210930_161537104](https://user-images.githubusercontent.com/8226248/135493031-9a5c6823-8be0-4dfd-adba-9d15cae0c238.jpg)

**Comment by JaehyunShim** [comment]
As advised by @christian-rauch, I will change the value from -2.9 to -3.4 and send a pull request. The reason why changing the values in the URDF and rerunning in the Perception PC or Operating PC was because the urdf file is read in the Control PC only once when the HW interface is launched (which is made by c0a438b).

@christian-rauch mentioned why there is another joint position limit info in this yaml file (https://github.com/ipab-slmc/nextagea_control/blob/master/nextagea_hardware_interface/config/joint_limits.yaml#L54)

**Comment by christian-rauch** [comment]
Fixed by https://github.com/ipab-slmc/nextagea/pull/43. You can used `Fixes !<PR>` to automatically close issues after their pull requests have been merged.
